Fix: Resolve react-to-print type error
The error `src/docs/UserGuide.tsx(27,5): error TS2353: Object literal may only specify known properties, and 'content' does not exist in type 'UseReactToPrintOptions'.` was resolved by updating the `useReactToPrint` options.